# Generated by Django 5.1.15 on 2026-03-23 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название')),
                ('authors', models.JSONField(blank=True, default=list, verbose_name='Авторы')),
                ('genre', models.CharField(blank=True, default='', max_length=120, verbose_name='Жанр')),
                ('language', models.CharField(blank=True, default='', max_length=80, verbose_name='Язык')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('cover', models.CharField(blank=True, default='web/img/placeholder-cover.svg', max_length=240, verbose_name='Обложка')),
                ('accent', models.CharField(blank=True, default='blue', max_length=32, verbose_name='Акцент')),
                ('isbn', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('display_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('avatar', models.CharField(blank=True, default='', max_length=8, verbose_name='Аватар')),
                ('status', models.CharField(blank=True, default='', max_length=160, verbose_name='Статус')),
                ('privacy', models.JSONField(blank=True, default=dict, verbose_name='Приватность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UID метки')),
                ('status', models.CharField(blank=True, default='', max_length=120, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'NFC-метка',
                'verbose_name_plural': 'NFC-метки',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default='', max_length=120, verbose_name='Устройство')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Локация')),
                ('last_seen', models.DateTimeField(verbose_name='Последняя активность')),
                ('refresh_token_hash', models.CharField(default=uuid.uuid4, max_length=80, unique=True, verbose_name='Хэш refresh токена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отозвана')),
                ('current', models.BooleanField(default=False, verbose_name='Текущая')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='web.btuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код экземпляра')),
                ('status', models.CharField(blank=True, default='', max_length=120, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='web.book', verbose_name='Книга')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_copies', to='web.btuser', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Экземпляр',
                'verbose_name_plural': 'Экземпляры',
            },
        ),
        migrations.CreateModel(
            name='NfcScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('place', models.CharField(blank=True, default='', max_length=160, verbose_name='Место')),
                ('payload', models.TextField(blank=True, default='', verbose_name='Данные')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='web.btuser', verbose_name='Пользователь')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='web.nfctag', verbose_name='NFC-метка')),
            ],
            options={
                'verbose_name': 'Сканирование',
                'verbose_name_plural': 'Сканирования',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Сканирование', 'Сканирование'), ('Передача', 'Передача'), ('Ожидание', 'Ожидание'), ('Подготовка', 'Подготовка')], max_length=32, verbose_name='Тип события')),
                ('date_time', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('place_text', models.CharField(blank=True, default='', max_length=160, verbose_name='Место')),
                ('text', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('source', models.CharField(blank=True, default='Маршрут BookTrail', max_length=160, verbose_name='Источник')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='web.copy', verbose_name='Экземпляр книги')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='web.btuser', verbose_name='Пользователь')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='web.nfcscan', verbose_name='Сканирование')),
                ('nfc_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='web.nfctag', verbose_name='NFC-метка')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=160, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('kind', models.CharField(blank=True, default='', max_length=80, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='web.btuser', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Скор')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Пояснение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='web.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='web.btuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Оценка')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('moderation_status', models.CharField(choices=[('Опубликован', 'Опубликован'), ('На модерации', 'На модерации'), ('Отклонён', 'Отклонён')], default='Опубликован', max_length=24, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='web.btuser', verbose_name='Автор')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='web.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='TagBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Дата привязки')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_binds', to='web.copy', verbose_name='Экземпляр книги')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_binds_created', to='web.btuser', verbose_name='Создал')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binds', to='web.nfctag', verbose_name='NFC-метка')),
            ],
            options={
                'verbose_name': 'Привязка NFC-метки',
                'verbose_name_plural': 'Привязки NFC-меток',
            },
        ),
        migrations.CreateModel(
            name='SemanticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Профиль')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_profiles', to='web.book', verbose_name='Книга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_profiles', to='web.btuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Семантический профиль',
                'verbose_name_plural': 'Семантические профили',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('book__isnull', True), ('user__isnull', False)), models.Q(('book__isnull', False), ('user__isnull', True)), _connector='OR'), name='semantic_profile_exactly_one_target')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначено')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='web.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='web.btuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_role')],
            },
        ),
    ]
