# Generated by Django 5.1.15 on 2026-04-11 18:45

import json

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def _username_from_email(email: str, user_id: int) -> str:
    local_part = (email or '').split('@', 1)[0].strip().lower()
    local_part = slugify(local_part).replace('-', '_')
    return local_part or f'user_{user_id}'


def _language_code(name: str) -> str:
    mapping = {
        'Русский': 'ru',
        'English': 'en',
    }
    if name in mapping:
        return mapping[name]
    slug = slugify(name, allow_unicode=False).replace('-', '')
    return (slug[:8] or 'lang').lower()


def forwards(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    BtUser = apps.get_model('web', 'BtUser')
    UserProfile = apps.get_model('web', 'UserProfile')
    Genre = apps.get_model('web', 'Genre')
    Language = apps.get_model('web', 'Language')
    Author = apps.get_model('web', 'Author')
    Book = apps.get_model('web', 'Book')
    BookAuthor = apps.get_model('web', 'BookAuthor')
    NfcScan = apps.get_model('web', 'NfcScan')
    Move = apps.get_model('web', 'Move')
    Copy = apps.get_model('web', 'Copy')
    NfcTag = apps.get_model('web', 'NfcTag')
    Review = apps.get_model('web', 'Review')
    Recommendation = apps.get_model('web', 'Recommendation')
    Notification = apps.get_model('web', 'Notification')

    existing_usernames = set(User.objects.values_list('username', flat=True))
    for legacy_user in BtUser.objects.order_by('id'):
        username = _username_from_email(legacy_user.email, legacy_user.id)
        base_username = username
        suffix = 1
        while username in existing_usernames:
            suffix += 1
            username = f'{base_username}_{suffix}'
        existing_usernames.add(username)

        parts = legacy_user.display_name.split(maxsplit=1)
        first_name = parts[0] if parts else ''
        last_name = parts[1] if len(parts) > 1 else ''
        user, created = User.objects.get_or_create(
            id=legacy_user.id,
            defaults={
                'username': username,
                'email': legacy_user.email,
                'first_name': first_name,
                'last_name': last_name,
                'is_active': legacy_user.is_active,
                'is_staff': False,
                'is_superuser': False,
                'date_joined': legacy_user.created_at or timezone.now(),
                'password': '!',
            },
        )
        if not created:
            user.username = username
            user.email = legacy_user.email
            user.first_name = first_name
            user.last_name = last_name
            user.is_active = legacy_user.is_active
            user.save(update_fields=['username', 'email', 'first_name', 'last_name', 'is_active'])

        privacy = legacy_user.privacy or {}
        UserProfile.objects.update_or_create(
            user_id=user.id,
            defaults={
                'avatar': legacy_user.avatar,
                'status': legacy_user.status,
                'show_profile': privacy.get('show_profile', True),
                'share_reviews': privacy.get('share_reviews', True),
                'nfc_visibility': privacy.get('nfc_visibility', False),
                'created_at': legacy_user.created_at or timezone.now(),
                'updated_at': legacy_user.updated_at or timezone.now(),
            },
        )

    for book in Book.objects.order_by('id'):
        if book.genre:
            genre, _ = Genre.objects.get_or_create(
                name=book.genre,
                defaults={'slug': slugify(book.genre, allow_unicode=True)},
            )
            book.genre_fk_id = genre.id
        if book.language:
            language, _ = Language.objects.get_or_create(
                name=book.language,
                defaults={'code': _language_code(book.language)},
            )
            book.language_fk_id = language.id
        book.save(update_fields=['genre_fk', 'language_fk'])

        if isinstance(book.authors, list):
            authors = book.authors
        else:
            try:
                authors = json.loads(book.authors or '[]')
            except (json.JSONDecodeError, TypeError):
                authors = []
        for order, author_name in enumerate(authors):
            author, _ = Author.objects.get_or_create(name=author_name)
            BookAuthor.objects.get_or_create(book_id=book.id, author_id=author.id, defaults={'sort_order': order})

    scan_by_id = {scan.id: scan for scan in NfcScan.objects.select_related('tag')}
    for move in Move.objects.exclude(scan_id__isnull=True):
        scan = scan_by_id.get(move.scan_id)
        if not scan:
            continue
        if not move.payload:
            move.payload = scan.payload or ''
        if not move.place_text:
            move.place_text = scan.place or ''
        if not move.nfc_tag_id:
            move.nfc_tag_id = scan.tag_id
        move.save(update_fields=['payload', 'place_text', 'nfc_tag'])

    copy_status_map = {
        'В движении': 'in_transit',
        'У читателя': 'with_reader',
        'Ожидает следующего читателя': 'waiting',
        'На полке сообщества': 'community_shelf',
        'В обработке': 'processing',
    }
    for copy in Copy.objects.all():
        copy.status = copy_status_map.get(copy.status, 'waiting')
        copy.save(update_fields=['status'])

    move_type_map = {
        'Сканирование': 'scan',
        'Передача': 'transfer',
        'Ожидание': 'waiting',
        'Подготовка': 'prep',
    }
    for move in Move.objects.all():
        move.event_type = move_type_map.get(move.event_type, 'scan')
        move.save(update_fields=['event_type'])

    tag_status_map = {
        'Свободна': 'available',
        'Привязана': 'bound',
        'Архивирована': 'archived',
    }
    for tag in NfcTag.objects.all():
        tag.status = tag_status_map.get(tag.status, 'available')
        tag.save(update_fields=['status'])

    moderation_map = {
        'Опубликован': 'published',
        'На модерации': 'pending',
        'Отклонён': 'rejected',
    }
    for review in Review.objects.all():
        review.moderation_status = moderation_map.get(review.moderation_status, 'published')
        review.save(update_fields=['moderation_status'])

    notification_map = {
        'Перемещение': 'move',
        'Отзыв': 'review',
        'Рекомендация': 'recommendation',
        'NFC': 'nfc',
        '': 'move',
    }
    for notification in Notification.objects.all():
        notification.kind = notification_map.get(notification.kind, notification.kind or 'move')
        notification.save(update_fields=['kind'])

    seen_reviews = set()
    for review in Review.objects.order_by('id'):
        key = (review.book_id, review.author_id)
        if key in seen_reviews and review.author_id is not None:
            review.delete()
        else:
            seen_reviews.add(key)

    seen_recommendations = set()
    for recommendation in Recommendation.objects.order_by('id'):
        key = (recommendation.user_id, recommendation.book_id)
        if key in seen_recommendations:
            recommendation.delete()
        else:
            seen_recommendations.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Язык')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, default='', max_length=8, verbose_name='Аватар')),
                ('status', models.CharField(blank=True, default='', max_length=160, verbose_name='Статус')),
                ('show_profile', models.BooleanField(default=True, verbose_name='Показывать профиль')),
                ('share_reviews', models.BooleanField(default=True, verbose_name='Делиться отзывами')),
                ('nfc_visibility', models.BooleanField(default=False, verbose_name='Показывать NFC-статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booktrail_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='web.author', verbose_name='Автор')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='web.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Автор книги',
                'verbose_name_plural': 'Авторы книг',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='move',
            name='payload',
            field=models.TextField(blank=True, default='', verbose_name='Данные'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.language'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.DeleteModel(name='SemanticProfile'),
        migrations.AlterField(
            model_name='authsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_copies', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='move',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tagbind',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_binds_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booktrail_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(model_name='move', name='scan'),
        migrations.DeleteModel(name='NfcScan'),
        migrations.RemoveField(model_name='book', name='authors'),
        migrations.RemoveField(model_name='book', name='genre'),
        migrations.RemoveField(model_name='book', name='language'),
        migrations.RenameField(model_name='book', old_name='genre_fk', new_name='genre'),
        migrations.RenameField(model_name='book', old_name='language_fk', new_name='language'),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='web.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='web.language', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='web.BookAuthor', to='web.author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('in_transit', 'В движении'), ('with_reader', 'У читателя'), ('waiting', 'Ожидает следующего читателя'), ('community_shelf', 'На полке сообщества'), ('processing', 'В обработке')], default='waiting', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='move',
            name='event_type',
            field=models.CharField(choices=[('scan', 'Сканирование'), ('transfer', 'Передача'), ('waiting', 'Ожидание'), ('prep', 'Подготовка')], max_length=16, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='status',
            field=models.CharField(choices=[('available', 'Свободна'), ('bound', 'Привязана'), ('archived', 'Архивирована')], default='available', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('move', 'Перемещение'), ('review', 'Отзыв'), ('recommendation', 'Рекомендация'), ('nfc', 'NFC')], default='move', max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('pending', 'На модерации'), ('rejected', 'Отклонён')], default='published', max_length=16, verbose_name='Статус модерации'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='uniq_recommendation_per_user_book'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('book', 'author'), name='uniq_review_per_user_book'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author'), name='uniq_book_author'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'sort_order'), name='uniq_book_author_order'),
        ),
        migrations.DeleteModel(name='BtUser'),
    ]
