# Generated by Django 5.1.15 on 2026-04-11 19:38

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    CopyStatus = apps.get_model('web', 'CopyStatus')
    MoveEventType = apps.get_model('web', 'MoveEventType')
    MoveSource = apps.get_model('web', 'MoveSource')
    NfcTagStatus = apps.get_model('web', 'NfcTagStatus')
    NotificationKind = apps.get_model('web', 'NotificationKind')
    ReviewModerationStatus = apps.get_model('web', 'ReviewModerationStatus')
    Copy = apps.get_model('web', 'Copy')
    Move = apps.get_model('web', 'Move')
    NfcTag = apps.get_model('web', 'NfcTag')
    Notification = apps.get_model('web', 'Notification')
    Review = apps.get_model('web', 'Review')

    copy_statuses = {
        code: CopyStatus.objects.get_or_create(code=code, defaults={'title': title})[0]
        for code, title in [
            ('in_transit', 'В движении'),
            ('with_reader', 'У читателя'),
            ('waiting', 'Ожидает следующего читателя'),
            ('community_shelf', 'На полке сообщества'),
            ('processing', 'В обработке'),
        ]
    }
    move_event_types = {
        code: MoveEventType.objects.get_or_create(code=code, defaults={'title': title})[0]
        for code, title in [
            ('scan', 'Сканирование'),
            ('transfer', 'Передача'),
            ('waiting', 'Ожидание'),
            ('prep', 'Подготовка'),
        ]
    }
    move_sources = {
        code: MoveSource.objects.get_or_create(code=code, defaults={'title': title})[0]
        for code, title in [
            ('booktrail_route', 'Маршрут BookTrail'),
        ]
    }
    nfc_tag_statuses = {
        code: NfcTagStatus.objects.get_or_create(code=code, defaults={'title': title})[0]
        for code, title in [
            ('available', 'Свободна'),
            ('bound', 'Привязана'),
            ('archived', 'Архивирована'),
        ]
    }
    notification_kinds = {
        code: NotificationKind.objects.get_or_create(code=code, defaults={'title': title})[0]
        for code, title in [
            ('move', 'Перемещение'),
            ('review', 'Отзыв'),
            ('recommendation', 'Рекомендация'),
            ('nfc', 'NFC'),
        ]
    }
    review_statuses = {
        code: ReviewModerationStatus.objects.get_or_create(code=code, defaults={'title': title})[0]
        for code, title in [
            ('published', 'Опубликован'),
            ('pending', 'На модерации'),
            ('rejected', 'Отклонён'),
        ]
    }

    for row in Copy.objects.all():
        row.status_fk_id = copy_statuses.get(row.status, copy_statuses['waiting']).id
        row.save(update_fields=['status_fk'])

    for row in Move.objects.all():
        row.event_type_fk_id = move_event_types.get(row.event_type, move_event_types['scan']).id
        source_code = 'booktrail_route' if row.source == 'Маршрут BookTrail' else 'booktrail_route'
        row.source_fk_id = move_sources[source_code].id
        row.save(update_fields=['event_type_fk', 'source_fk'])

    for row in NfcTag.objects.all():
        row.status_fk_id = nfc_tag_statuses.get(row.status, nfc_tag_statuses['available']).id
        row.save(update_fields=['status_fk'])

    for row in Notification.objects.all():
        row.kind_fk_id = notification_kinds.get(row.kind, notification_kinds['move']).id
        row.save(update_fields=['kind_fk'])

    for row in Review.objects.all():
        row.moderation_status_fk_id = review_statuses.get(row.moderation_status, review_statuses['published']).id
        row.save(update_fields=['moderation_status_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_author_bookauthor_genre_language_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус экземпляра',
                'verbose_name_plural': 'Статусы экземпляров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MoveEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MoveSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник события',
                'verbose_name_plural': 'Источники событий',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NfcTagStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус NFC-метки',
                'verbose_name_plural': 'Статусы NFC-меток',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NotificationKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ReviewModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус модерации',
                'verbose_name_plural': 'Статусы модерации',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='copy',
            name='status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.copystatus'),
        ),
        migrations.AddField(
            model_name='move',
            name='event_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.moveeventtype'),
        ),
        migrations.AddField(
            model_name='move',
            name='source_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.movesource'),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.nfctagstatus'),
        ),
        migrations.AddField(
            model_name='notification',
            name='kind_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.notificationkind'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web.reviewmoderationstatus'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(model_name='copy', name='status'),
        migrations.RemoveField(model_name='move', name='event_type'),
        migrations.RemoveField(model_name='move', name='source'),
        migrations.RemoveField(model_name='nfctag', name='status'),
        migrations.RemoveField(model_name='notification', name='kind'),
        migrations.RemoveField(model_name='review', name='moderation_status'),
        migrations.RenameField(model_name='copy', old_name='status_fk', new_name='status'),
        migrations.RenameField(model_name='move', old_name='event_type_fk', new_name='event_type'),
        migrations.RenameField(model_name='move', old_name='source_fk', new_name='source'),
        migrations.RenameField(model_name='nfctag', old_name='status_fk', new_name='status'),
        migrations.RenameField(model_name='notification', old_name='kind_fk', new_name='kind'),
        migrations.RenameField(model_name='review', old_name='moderation_status_fk', new_name='moderation_status'),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='web.copystatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='move',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='web.moveeventtype', verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='move',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='web.movesource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='web.nfctagstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='web.notificationkind', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='web.reviewmoderationstatus', verbose_name='Статус модерации'),
        ),
    ]
