from .base import *  # noqa: F401,F403


DEBUG = env_bool('DJANGO_DEBUG', False)

if SECRET_KEY == 'django-insecure-booktrail-dev-key':
    raise RuntimeError('DJANGO_SECRET_KEY must be set in production.')

if not ALLOWED_HOSTS:
    raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set in production.')

CSRF_COOKIE_SECURE = True if env('DJANGO_CSRF_COOKIE_SECURE') is None else CSRF_COOKIE_SECURE
SESSION_COOKIE_SECURE = True if env('DJANGO_SESSION_COOKIE_SECURE') is None else SESSION_COOKIE_SECURE
SECURE_SSL_REDIRECT = True if env('DJANGO_SECURE_SSL_REDIRECT') is None else SECURE_SSL_REDIRECT
SECURE_HSTS_SECONDS = int(env('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if env('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS') is None else SECURE_HSTS_INCLUDE_SUBDOMAINS
SECURE_HSTS_PRELOAD = True if env('DJANGO_SECURE_HSTS_PRELOAD') is None else SECURE_HSTS_PRELOAD

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
